### PR TITLE
update ci to include coverage

### PR DESCRIPTION
**Pull request by DeveloperInProgress**
# Description
Update CI to include coverage reports for tests

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] I have tested locally
- [ ] I have performed a self review of my changes
- [ ] Updated any relevant documentation
- [ ] Linked to any relevant issues
- [ ] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My code is up to date with the base branch
- [ ] I have updated relevant changelogs. [We suggest using chan](https://github.com/geut/chan/tree/main/packages/chan)

### CODE REVIEW

**Comment by stwiname** [comment]
It seems like these tests are failing to run:
```
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
```

**Comment by stwiname** [comment]
> > It seems like these tests are failing to run:
> > ```
> > Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure what wasm has to do with things
> 
> happened after updating to node 18. seems to come from a package that does coverage formatting.

Setting `--no-experimental-fetch` doesn't scale well if we have to add that when we run locally with each SDK. Is there a better solution like updating jest?

**Comment by DeveloperInProgress** [comment]
> Setting `--no-experimental-fetch` doesn't scale well if we have to add that when we run locally with each SDK. Is there a better solution like updating jest?

Updating jest fixed the issue

**Review by stwiname — APPROVED** [review]
This looks good. Just the one conflict. 

Can we apply these changes to other sdks

**Pull request merged**
